import '../models/badge.dart';

/// All badge definitions. The checkUnlock function receives a stats map:
/// { 'pagesRead': int, 'booksRead': int, 'streakDays': int,
///   'focusSessionCount': int, 'focusMinutesTotal': int }
final List<BadgeDefinition> allBadges = [
  // ── Reading Badges ──
  BadgeDefinition(
    id: 'first_page',
    nameKey: 'badgeFirstPage',
    descriptionKey: 'badgeFirstPageDesc',
    icon: '📖',
    category: BadgeCategory.reading,
    checkUnlock: (stats) => (stats['pagesRead'] ?? 0) >= 1,
  ),
  BadgeDefinition(
    id: 'fifty_pages',
    nameKey: 'badgeFiftyPages',
    descriptionKey: 'badgeFiftyPagesDesc',
    icon: '📄',
    category: BadgeCategory.reading,
    checkUnlock: (stats) => (stats['pagesRead'] ?? 0) >= 50,
  ),
  BadgeDefinition(
    id: 'two_hundred_pages',
    nameKey: 'badgeTwoHundredPages',
    descriptionKey: 'badgeTwoHundredPagesDesc',
    icon: '📑',
    category: BadgeCategory.reading,
    checkUnlock: (stats) => (stats['pagesRead'] ?? 0) >= 200,
  ),
  BadgeDefinition(
    id: 'five_hundred_pages',
    nameKey: 'badgeFiveHundredPages',
    descriptionKey: 'badgeFiveHundredPagesDesc',
    icon: '📋',
    category: BadgeCategory.reading,
    checkUnlock: (stats) => (stats['pagesRead'] ?? 0) >= 500,
  ),
  BadgeDefinition(
    id: 'page_turner',
    nameKey: 'badgePageTurner',
    descriptionKey: 'badgePageTurnerDesc',
    icon: '📚',
    category: BadgeCategory.reading,
    checkUnlock: (stats) => (stats['pagesRead'] ?? 0) >= 1000,
  ),
  BadgeDefinition(
    id: 'marathon_reader',
    nameKey: 'badgeMarathonReader',
    descriptionKey: 'badgeMarathonReaderDesc',
    icon: '🏃',
    category: BadgeCategory.reading,
    checkUnlock: (stats) => (stats['pagesRead'] ?? 0) >= 10000,
  ),
  BadgeDefinition(
    id: 'first_book',
    nameKey: 'badgeFirstBook',
    descriptionKey: 'badgeFirstBookDesc',
    icon: '🎉',
    category: BadgeCategory.reading,
    checkUnlock: (stats) => (stats['booksRead'] ?? 0) >= 1,
  ),
  BadgeDefinition(
    id: 'three_books',
    nameKey: 'badgeThreeBooks',
    descriptionKey: 'badgeThreeBooksDesc',
    icon: '🥉',
    category: BadgeCategory.reading,
    checkUnlock: (stats) => (stats['booksRead'] ?? 0) >= 3,
  ),
  BadgeDefinition(
    id: 'bookworm',
    nameKey: 'badgeBookworm',
    descriptionKey: 'badgeBookwormDesc',
    icon: '🐛',
    category: BadgeCategory.reading,
    checkUnlock: (stats) => (stats['booksRead'] ?? 0) >= 10,
  ),
  BadgeDefinition(
    id: 'century_club',
    nameKey: 'badgeCenturyClub',
    descriptionKey: 'badgeCenturyClubDesc',
    icon: '💯',
    category: BadgeCategory.reading,
    checkUnlock: (stats) => (stats['booksRead'] ?? 0) >= 100,
  ),

  // ── Streak Badges ──
  BadgeDefinition(
    id: 'getting_started',
    nameKey: 'badgeGettingStarted',
    descriptionKey: 'badgeGettingStartedDesc',
    icon: '🌱',
    category: BadgeCategory.streak,
    checkUnlock: (stats) => (stats['streakDays'] ?? 0) >= 2,
  ),
  BadgeDefinition(
    id: 'three_day_streak',
    nameKey: 'badgeThreeDayStreak',
    descriptionKey: 'badgeThreeDayStreakDesc',
    icon: '🌿',
    category: BadgeCategory.streak,
    checkUnlock: (stats) => (stats['streakDays'] ?? 0) >= 3,
  ),
  BadgeDefinition(
    id: 'five_day_streak',
    nameKey: 'badgeFiveDayStreak',
    descriptionKey: 'badgeFiveDayStreakDesc',
    icon: '✨',
    category: BadgeCategory.streak,
    checkUnlock: (stats) => (stats['streakDays'] ?? 0) >= 5,
  ),
  BadgeDefinition(
    id: 'on_fire',
    nameKey: 'badgeOnFire',
    descriptionKey: 'badgeOnFireDesc',
    icon: '🔥',
    category: BadgeCategory.streak,
    checkUnlock: (stats) => (stats['streakDays'] ?? 0) >= 7,
  ),
  BadgeDefinition(
    id: 'two_week_streak',
    nameKey: 'badgeTwoWeekStreak',
    descriptionKey: 'badgeTwoWeekStreakDesc',
    icon: '💪',
    category: BadgeCategory.streak,
    checkUnlock: (stats) => (stats['streakDays'] ?? 0) >= 14,
  ),
  BadgeDefinition(
    id: 'unstoppable',
    nameKey: 'badgeUnstoppable',
    descriptionKey: 'badgeUnstoppableDesc',
    icon: '⚡',
    category: BadgeCategory.streak,
    checkUnlock: (stats) => (stats['streakDays'] ?? 0) >= 30,
  ),
  BadgeDefinition(
    id: 'legend',
    nameKey: 'badgeLegend',
    descriptionKey: 'badgeLegendDesc',
    icon: '👑',
    category: BadgeCategory.streak,
    checkUnlock: (stats) => (stats['streakDays'] ?? 0) >= 100,
  ),
  BadgeDefinition(
    id: 'immortal',
    nameKey: 'badgeImmortal',
    descriptionKey: 'badgeImmortalDesc',
    icon: '🌟',
    category: BadgeCategory.streak,
    checkUnlock: (stats) => (stats['streakDays'] ?? 0) >= 365,
  ),

  // ── Focus Badges ──
  BadgeDefinition(
    id: 'first_focus',
    nameKey: 'badgeFirstFocus',
    descriptionKey: 'badgeFirstFocusDesc',
    icon: '🎯',
    category: BadgeCategory.focus,
    checkUnlock: (stats) => (stats['focusSessionCount'] ?? 0) >= 1,
  ),
  BadgeDefinition(
    id: 'focus_five',
    nameKey: 'badgeFocusFive',
    descriptionKey: 'badgeFocusFiveDesc',
    icon: '⏱️',
    category: BadgeCategory.focus,
    checkUnlock: (stats) => (stats['focusSessionCount'] ?? 0) >= 5,
  ),
  BadgeDefinition(
    id: 'focus_regular',
    nameKey: 'badgeFocusRegular',
    descriptionKey: 'badgeFocusRegularDesc',
    icon: '⏳',
    category: BadgeCategory.focus,
    checkUnlock: (stats) => (stats['focusSessionCount'] ?? 0) >= 20,
  ),
  BadgeDefinition(
    id: 'focus_master',
    nameKey: 'badgeFocusMaster',
    descriptionKey: 'badgeFocusMasterDesc',
    icon: '🎯',
    category: BadgeCategory.focus,
    checkUnlock: (stats) => (stats['focusSessionCount'] ?? 0) >= 50,
  ),
  BadgeDefinition(
    id: 'focus_hour',
    nameKey: 'badgeFocusHour',
    descriptionKey: 'badgeFocusHourDesc',
    icon: '🕐',
    category: BadgeCategory.focus,
    checkUnlock: (stats) => (stats['focusMinutesTotal'] ?? 0) >= 60,
  ),
  BadgeDefinition(
    id: 'focus_ten_hours',
    nameKey: 'badgeFocusTenHours',
    descriptionKey: 'badgeFocusTenHoursDesc',
    icon: '🕙',
    category: BadgeCategory.focus,
    checkUnlock: (stats) => (stats['focusMinutesTotal'] ?? 0) >= 600,
  ),

];
